In [1]:
import numpy as np

In [3]:
#1. What is a Python library? Why ^o we use Python libraries?

In [2]:
#What is python Library? A library is a collection of code that makes everyday tasks more efficient. Using Seaborn, for example, you can generate visualisations with just one line of code. 
#To create a chart from an object, you'd have to write a lot of code without a library like this.

In [6]:
#3. Fin^ the shape, size an^ ^imension of the following array?
'''[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''

'[[1, 2, 3, 4]\n[5, 6, 7, 8],\n[9, 10, 11, 12]]'

In [7]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr.shape

(3, 4)

In [9]:
arr.ndim

2

In [10]:
arr.size

12

In [11]:
#4. Write python co^e to access the first row of the following array?

In [12]:
arr[0]

array([1, 2, 3, 4])

In [13]:
#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

In [15]:
arr[2][3]

12

In [16]:
#Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

In [17]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11])

In [18]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [21]:
ar=np.random.randint(0,1 ,(3,3))
ar

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

In [23]:
#np.random.randn :It generates the number between [0,1) by using normal distribution wheras np.random.rand it generates the number 
#between [0,1) by using standarad gaussian distribution(mean 0 and variance 1)

In [24]:
#10. How to transpose the following array in NumPy?

In [25]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [27]:
#11. Consi^er the following matrix:
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
 #Index wiLe multiplication
# Matix multiplication
# Add both the maticK
# Subtact matix B from A
#Diide Matix B by A

In [37]:
matA2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
matB2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [38]:
matA2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
matB2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
matA2*matB2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [48]:
#matA2@matB2

In [49]:
matA2+matB2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [50]:
matB2-matA2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
matB2/matA2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
#Which function in Numpy can be use^ to swap the byte or^er of an array?

In [54]:
#The ndarray.byteswap() method swaps the bytes of the array elements. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place.

#Note: byteswap() method does not work on arrays of strings.

#Example
 
# Python program explaining  
# byteswap() function  
import numpy as geek 
  
# a is an array of integers. 
a = geek.array([1, 256, 100], dtype = np.int16) 
   
print(a.byteswap(True)) 

[  256     1 25600]


In [56]:
#What is the significance of the np.linalg.inv function?:to inverse the matrix

In [57]:
from numpy.linalg import inv

In [60]:
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [61]:
#What ^oes the np.reshape function ^o, an^ how is it use^?

In [62]:
#The . reshape() function rearranges the data in an ndarray into a new shape. The new shape must be compatible with the old one, though an index of -1 can
#be used to infer one dimension.

In [63]:
#What is broa^casting in Numpy?

In [64]:
#The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [65]:
#9. Write co^e to increase the ^imension of the following array?

In [66]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
arr.ndim

2

In [68]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [70]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])